### PR TITLE
Replacing explicit module check with hook

### PR DESCRIPTION
**Pull request by patric-eberle**
I replaced an out of date support for the i18nl10n module with a new hook.

### CODE REVIEW

**Comment by Toflar** [comment]
It's back end...shouldn't it be a callback rather than a hook then? Well, Contao itself is not consistent in that matter anyway... :)

**Comment by aschempp** [comment]
I guess that's a good point, because callbacks are tied to a specific DCA where hooks are not…

**Comment by patric-eberle** [comment]
True. I'm looking forward for your callback solution then and will try to create a workaround for my module in the meantime.

**Comment by aschempp** [comment]
Are you the developer of i18nl10n? Or how do you know it's outdated?

**Comment by patric-eberle** [comment]
Yes I'm the developer. The config value you're checking is no longer available since two versions.

**Comment by aschempp** [comment]
Implemented in b2b658a3dc1f89e09e53c581e202e54bd32181a5

You should set `DCA => config => languages` in an onload_callback to customize the options.

**Pull request closed without merging**
