### PR TITLE
hasTax() Shortcut - helping with tax exemption

### PR DESCRIPTION
**Pull request by cubex-hro**
Order Class shortcut added to find out if an order has tax or not.

### CODE REVIEW

**Comment by aschempp** [comment]
This could probably be added to the parent class, so we could check for taxes of a cart as well?

**Comment by cubex-hro** [comment]
That would be useful.

**Comment by aschempp** [comment]
Can you change the Pull Request accordingly?

**Comment by cubex-hro** [comment]
done :)

**Pull request merged**
