### PR TITLE
Consider sendNotificationMessage Hook

### PR DESCRIPTION
**Pull request by c4y**
Since Isotope uses Notification-Center it should support sendNotificationMessage Hook from Notification-Center. With this Bundle you can send different notifications dependant on product: https://github.com/postyou/isotope_notification_product_extension
This does actually not work because postsale.php removes the Hook. See #2174

### CODE REVIEW

**Comment by fritzmg** [comment]
@aschempp why does the postsale entry point remove hooks at all? Shouldn't it only remove hooks that are known to cause issues for whatever reason?

**Comment by aschempp** [comment]
@c4y thanks for the PR, I'll merge this in the next release.

@fritzmg because there were various issue with hooks due to the fact that not the full system is initialized/no actual page is there.

**Review by aschempp — APPROVED** [review]

**Comment by bennyborn** [comment]
@aschempp While I welcome the addition of `sendNotificationMessage` to the whitelist I still think this might be the wrong way. The core itself comes with a manageable amount of hooks so why not just create a blacklist with the hooks known to cause trouble? I'm pretty certain there will be more problems using a whitelist approach in the future.

**Comment by aschempp** [comment]
The postsale process should not be considered a safe environment for any hook we don't know we support it. There have been plenty of random issues with it and third-party extensions, and the current solution seems to work fine.

**Pull request merged**
