### PR TITLE
Fix some of MySQL 8 compatibility issues

### PR DESCRIPTION
**Pull request by qzminski**

### CODE REVIEW

**Comment by Toflar** [comment]
We could use `Database::quoteIdentifier()` here but quoting directly is okay for me too. I'll leave that up to @aschempp to decide.

**Comment by fritzmg** [comment]
How does the core deal with that usually?

**Comment by aschempp** [comment]
Instead of escaping, we should prefix the fields with the table name. That will also fix any potential issues when joining related table. See https://github.com/isotope/core/pull/2088/files for some more. @qzminski can you please update the PR?

**Comment by qzminski** [comment]
Updated 👍🏻

**Pull request merged**
