### PR TITLE
Allow composer plugins

### PR DESCRIPTION
**Pull request by bytehead**

### CODE REVIEW

**Comment by aschempp** [comment]
I just allowed them in my global composer setup, do we really need to add that to every package? 😂

**Comment by bytehead** [comment]
🤷 I don't actually know what is the best solution. If somebody has not allowed it globally, it blocks the installation process.

**Comment by aschempp** [comment]
I don't think it does. This only fixes the plugins if you checked out `isotope/core` locally and install its dependencies, right? It does not block anyone from using Isotope.

**Comment by bytehead** [comment]
You're possibly right 😬

**Pull request closed without merging**
