### PR TITLE
Remove `patchwork/utf-8` dependency since it is abandoned

### LINKED ISSUE #2548: Replace abandoned patchwork/utf8 dependency
It would be great to replace the [patchwork/utf8](https://packagist.org/packages/patchwork/utf8) dependency since it is abandoned.
It is only used four times in the [DC_ProductData](https://github.com/isotope/core/blob/46fb9d424e063ad914c1131fcb369a3478cd41bb/system/modules/isotope/drivers/DC_ProductData.php) file to sort some `$options_sorter`:
```php
        // Sort by option values
        uksort($options_sorter, array(Utf8::class, 'strnatcasecmp'));
```

There also exists the [strnatcasecmp](https://www.php.net/manual/en/function.strnatcasecmp.php) function directly in PHP, but I am unsure if it works the same for non ASCII characters (and if thats even relevant).

If this can simply be replaced then I can also create a PR for this.

### PR DESCRIPTION
**Pull request by f-schnabel**
Fixes #2548

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
The `symfony/string` dependency needs to be added as well.

**Comment by f-schnabel** [comment]
@fritzmg thank you. Just `5.4^` or `5.4^ || 6.0^`?

**Comment by fritzmg** [comment]
I suppose just `^5.4` will suffice, since Isotope 2.x will not receive a release for Contao 5+. But technically you can allow higher versions, if compatible.

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
Thanks for your pull request! I'm sorry I didn't see it early enought and fixed this myself in 31bcc536e22980148bc71de4744653f350f8c881 🙈

**Pull request closed without merging**
