### PR TITLE
Fixed missing space in class list

### PR DESCRIPTION
**Pull request by bytehead**
Fixed a missing space - got classes in my markup like `col_4col_last`.

### CODE REVIEW

**Comment by aschempp** [comment]
:+1:  but please add the whitespace to the echo statement instead of in general

**Comment by bytehead** [comment]
I tried to match up with the [existing coding style](https://github.com/isotope/core/pull/1552/files#diff-c7b200a123582e1ff0d1b9d236120074R52).

**Comment by aschempp** [comment]
Well you can see there's a whitespace in the mentioned line. It's just on the other side of the string…

**Comment by bytehead** [comment]
I talk about the blue marked one...
bildschirmfoto 2015-10-12 um 21 37 45

**Comment by bytehead** [comment]
Like in here 5075b0b14922f3bc0d837a3ea3d86261c886343d?

**Comment by aschempp** [comment]
Yeah, but we don't need a space at the end, just at the beginning. There already is a space at the end ^^

**Comment by aschempp** [comment]
Maybe you can fix the next line too so they are identical? Or let me know if you want me to make the adjustments ^^

**Comment by bytehead** [comment]
I will rebase the PR, if the changes are ok now.

**Comment by aschempp** [comment]
Looks good! Rebase to what? :D

**Comment by bytehead** [comment]
Squash the commits into one...?

**Comment by aschempp** [comment]
Ah, that's not necessary to me. However, we should fix that in the master/hotfix branch and not develop as it's a bug, right?

**Comment by bytehead** [comment]
Ok. I would say it's a bug.

**Pull request merged**
