### PR TITLE
Fix PHP 8 warning in order conditions form

### PR DESCRIPTION
**Pull request by ameotoko**
If order conditions form contains file upload field which is not mandatory, there will be a warning when the form is displayed:

```
ErrorException:
Warning: Undefined array key "FILES"

  at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/OrderConditions.php:123
  at Isotope\CheckoutStep\OrderConditions->generate()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php:325)
```

and later – when it is submitted:

```
ErrorException:
Warning: Undefined array key "FILES"

  at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/OrderConditions.php:105
```

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
Not sure that would be correct, because we're not threathing upload files as input fields if `$_SESSION['FILES']` is empty. I think we should use something like `$_SESSION['FILES'][$strField] ?? null` instead?

**Comment by ameotoko** [comment]
You mean in the `if` condition?

```php
if ($this->objForm->getWidget($strField) instanceof \uploadable && ($_SESSION['FILES'][$strField] ?? null))
```

**Comment by aschempp** [comment]
yeah, if the file is not uploaded, we shouldn't get the value from the form field, but just use an empty value. Casting (`??`) would do that I think?

**Comment by aschempp** [comment]
Looks like you only changed one of the two places? 🙃

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @ameotoko

**Comment by ameotoko** [comment]
I think my way is more concise. `!empty()` checks whether `$_SESSION['FILES'][$strField]` array key exists and has truthy value, which is exactly what we want. And if the condition is not satisfied, `$this->objForm->fetch($strField)` returns the proper default empty value for any widget, which can be `null` for `FormFileUpload` or empty array for `FineUploader`. Your version does not consider `FineUploader`.

**Comment by aschempp** [comment]
The way Contao currently works, I don't think we're ever supposed to retrieve the value of an uploadable field? Something we recently discussed while updating fineuploader for Contao 5, unfortunately there's no "standard" in Contao for that.

**Pull request merged**
