### PR TITLE
fix broken saferpay payment

### PR DESCRIPTION
**Pull request by plandolt**
[Fixes the completely broken saferpay payment.](https://github.com/isotope/core/issues/2306)

### CODE REVIEW

**Comment by aschempp** [comment]
Nice catch! Sorry I didn't read that correctly in https://github.com/isotope/core/issues/2306
Can you please revert the `use ...Response` statement, then I'd merge that asap.

**Comment by meier-simon** [comment]
Hello @aschempp 
I have now found and fixed the problem. 
Can you please do a rebase and merge the PR?

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @scuben and @meier-simon

**Comment by meier-simon** [comment]
Thank you @aschempp for merging the bug fix. 
Can you already say when you will release the new tag 2.8.4?

**Comment by aschempp** [comment]
Version 2.8.4 has just been released 🙃

**Pull request merged**
