### PR TITLE
Bump the contao-tablelookupwizard dependency version

### PR DESCRIPTION
**Pull request by qzminski**

### CODE REVIEW

**Comment by aschempp** [comment]
Did you test if everything still works? :D

**Comment by qzminski** [comment]
I have updated the DCA accordingly. Just one minor issue that cannot be fixed with the current version of the vendor:

2016-04-13 at 11 12

Once the below commit makes its way to the 3.2.0 release we are good to merge this PR.

https://github.com/terminal42/contao-tablelookupwizard/commit/6cbaa5fb55ce17b9e41a8cb93d70ce412fdb8692

**Comment by Toflar** [comment]
> Once the below commit makes its way to the 3.2.0 release we are good to merge this PR.

Feel free to merge it and notify me so I can publish in ER.

**Comment by qzminski** [comment]
I have released TableLookupWizard 3.2.0. So this PR can be merged as well.

**Comment by Toflar** [comment]
ER release 👍

**Pull request merged**
