### PR TITLE
Add customer turnover report #2415

### PR DESCRIPTION
**Pull request by henobi**
https://github.com/isotope/core/issues/2415
---

Hi,

I programmed a report to list the top customers of an isotope shop.
Especially in case of B2B shops this is usually a super useful info. 

The pull request is still work in progress.

Best,
Hendrik

Bildschirm­foto 2023-02-04 um 19 32 56

Bildschirm­foto 2023-02-04 um 19 33 59

### CODE REVIEW

**Comment by henobi** [comment]
I have developed the report on a isotope 2.6 system.
But as far as I can see, not much has changed in the reports from 2.6 to 2.8.

Unfortunately I don't have a newer version with customer data at hand to test it.

**Comment by aschempp** [comment]
thanks a lot! Let me know when the "work in progress" is done so I can check it out 😊

**Comment by error08** [comment]
Hi, cool that reports now has a little more life! I am currently working on various reports. In order to be able to better display the data with different diagrams, I have prepared the integration for the library apexcharts.

https://github.com/isotope/core/pull/2483

I have already changed the report SalesTotal, but I am still testing it.
In addition, I have already built a report regarding the top 10 customers. I will also soon hire this as PR.
But this has slightly different data than in your screenshot.

Other ideas for future reports:
- Customers by country & zip code
- Evaluation of AVO (Average Value Order)
- Member registrations
- Percentage usage of coupons

Feel free to write more ideas.

**Comment by aschempp** [comment]
any update on this report? Would be great to have it in Isotope 2.9 😎

**Comment by henobi** [comment]
Hello @aschempp,
I will finalize it and test it the next month. Thanks for your patience.
Best, Hendrik

**Comment by henobi** [comment]
Hi @aschempp,
tested it locally and it works.
BR, Hendrik

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @henobi ! I changed the report to be in the member section and removed the german translations, since they are managed on www.transifex.com.

**Comment by henobi** [comment]
Awesome @aschempp! Thank you!

**Pull request merged**
