### PR TITLE
Respect shipping exempt when calculating weight

### PR DESCRIPTION
**Pull request by tristanlins**
Otherwise the weight exclusion of shipping modules will not be correct for products that are exempted from shipping.

### CODE REVIEW

**Comment by tristanlins** [comment]
I'm sure there are more places where this check is missing...

**Comment by aschempp** [comment]
Why would you add a weight to the product if it's exempted from shipping? I mean just don't add the value to the product / the field to the product type?

**Comment by tristanlins** [comment]
The product is a dual product, with 2 variants. A print and a download version. But the weight is not set on the print variant, it is set on the main product.

**Comment by aschempp** [comment]
> The product is a dual product, with 2 variants. A print and a download version. But the weight is not set on the print variant, it is set on the main product.

I think that's an incorrect configuration of your shop. Still I see your point, I'm just not sure if it makes sense to check for this. With the correct configuration the admin would be able to choose if a shipping-exempted product should still be calculated (for whatever reason), which is not possible with your change…

/cc @Toflar @qzminski any opinions?

**Comment by Toflar** [comment]
Well, in this case I'm probably with @tristanlins here. It's the same product, just in an other variant. It has the same description, probably the same price, same author, same ISBN etc. One variant is just downloadable and the other is not. However, I think the implementation is wrong.

**Comment by aschempp** [comment]
It's the same product, but a different type. If you would sell two different versions of a book, they would also have two different weights, so a config in the variant makes sense.

As an example: https://de.wikipedia.org/wiki/Taschenbuch
> Ein Taschenbuch […] ist ein kleinformatiges Buch mit gewöhnlich weichem Einband. Es wird […] meist einige Zeit nach den höherwertigen fest (engl. „Hardcover“) oder weich („Broschur“) gebundenen Ausgaben veröffentlicht.

**Comment by Toflar** [comment]
Ah I misunderstood then.

> But the weight is not set on the print variant, it is set on the main product.

That's obviously a misconfiguration. The weight has to be set in the variant.

**Comment by tristanlins** [comment]
What about collection by the customer (Selbstabholer)? 
An item that is excluded from shipping must not only downloadable.

**Comment by aschempp** [comment]
That would be a shipping method not a product attribute?

**Comment by tristanlins** [comment]
I disagree, in the past I had build a shop with another software. My customer sells wooden products. Some are available for shipping and some only for collection by the customer. But when you buy two products, one for shipping and one for collection by the customer you can still select another shipping method for the first product. If you say this is a product attribute, why does the "except from shipping" attribute exist? It make no sense then.

**Comment by aschempp** [comment]
> If you say "collection by the customer" is a shipping method, not a product attribute, why does the "except from shipping" attribute exist? It make no sense then.

Because if you have only products that are not shipped, the shop does not ask for a shipping method at all. Again, the solution to your problem is very simple: do not enter a weight for the products not to be calculated. What's the problem with that? Even the field label is *Shipping weight* …

**Comment by tristanlins** [comment]
I agree that my setup is wrong.
But the behavior of your field is still wrong. It is valid that you have products with weight (e.g. for price calculation), but these products are excepted from shipping.

**Pull request closed without merging**
