### PR TITLE
Output actual exception message in postsale

### PR DESCRIPTION
**Pull request by richardhj**
I thought, the actual exception message would be helpful for debugging.
Just now, I have the stack trace, but not the resulting exception message.

For example, this is the output in my postsale log:
```
[02-Aug-2017 22:02:30] Exception in post-sale request
#0 /opt/users/www/system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('SELECT id, name...')
#1 /opt/users/www/composer/vendor/codefog/contao-haste/library/Haste/Util/Format.php(149): Contao\Database->query('SELECT id, name...')
#2 /opt/users/www/composer/vendor/codefog/contao-haste/library/Haste/Util/Format.php(123): Haste\Util\Format::dcaValueFromArray(Array, NULL, NULL)
#3 /opt/users/www/system/modules/cfg_isotope_stock_management/src/Entry/AbstractEntry.php(121): Haste\Util\Format::dcaValue('tl_iso_product', 'groups', NULL)
#4 /opt/users/www/system/modules/cfg_isotope_stock_management/src/Entry/AbstractEntry.php(97): Codefog\IsotopeStockManagement\Entry\AbstractEntry->sendOutOfStockNotification()
#5 /opt/users/www/system/modules/cfg_isotope_stock_management/src/Hooks.php(132): Codefog\IsotopeStockManagement\Entry\AbstractEntry->save()
#6 /opt/users/www/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php(186): Codefog\IsotopeStockManagement\Hooks->postCheckout(Object(Isotope\Model\ProductCollection\Order), Array)
#7 /opt/users/www/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php(74): Isotope\Model\ProductCollection\Order->checkout()
#8 /opt/users/www/system/modules/isotope/postsale.php(178): Isotope\Model\Payment\Paypal->processPostsale(Object(Isotope\Model\ProductCollection\Order))
#9 /opt/users/www/system/modules/isotope/postsale.php(240): Isotope\PostSale->run()
#10 {main}
```

### CODE REVIEW

**Comment by richardhj** [comment]
Duplicate of #1835, #1833

**Comment by aschempp** [comment]
We should also remove the invalid `sprintf` arguments to the `System::log` call.

**Comment by richardhj** [comment]
I think you should rather choose #1835 @aschempp ;-) This is already done there :-)

**Comment by aschempp** [comment]
Yeah, but it's incorrectly adding file and line which is already present in the trace ;-)

**Comment by richardhj** [comment]
RFC then @aschempp @fritzmg

**Comment by fritzmg** [comment]
> Yeah, but it's incorrectly adding file and line which is already present in the trace ;-)

No, neither file nor line is present in the trace.

**Comment by fritzmg** [comment]
Oh, you meant @richardhj PR, which simply converts the Exception to string, which includes the exception information _and_ the trace.

However @richardhj in your example output, the actual exception is still missing. Is that from before or after the change?

**Comment by richardhj** [comment]
As stated in the [manual](http://php.net/manual/de/exception.tostring.php#refsect1-exception.tostring-examples), the exception including the line and file and the following stack trace are given.
I changed to string casting of the exception afterwards.

**Comment by fritzmg** [comment]
Alight, was just confused/wondering :)

**Pull request merged**
