### PR TITLE
CurrencySpace with a non-breaking space

### PR DESCRIPTION
**Pull request by michelbalzer**
siehe #1628

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks!

Two things:
 1. Why not use `&nbsp;`?
 2. We must only output a HTML character if the output type is HTML (see the method argument).

**Comment by michelbalzer** [comment]
To 1.) Think I saw somewhere else in Isotope that the &# declaration was used. Otherwise there was no specific reason. Both should work.

To 2.) uhm, yes, my bad. The non-html version is used in non-html mails for example, right? We could directly put the character in it.

Von unterwegs gesendet

**Comment by michelbalzer** [comment]
As I researched: &#160; is faster ;)

Von unterwegs gesendet

**Comment by aschempp** [comment]
> The non-html version is used in non-html mails for example, right? We could directly put the character in it.

Correct, that's for plain text mails for example. Can you update the PR?

**Comment by michelbalzer** [comment]
Uhm, which one do I have to replace?

**Comment by aschempp** [comment]
Personally, I would prefer both. `&nbsp;` is easier to read for most users/developers, that should always be more important that theoretical performance. And we also must not use HTML in non-HTML mode.

**Comment by aschempp** [comment]
Merged in 4aa8fdc08619571cf1e8a39c935704033fff2ae3

**Pull request closed without merging**
