### PR TITLE
Added hook triggered when address data is updated

### PR DESCRIPTION
**Pull request by qzminski**
See #1473

### CODE REVIEW

**Comment by aschempp** [comment]
I don't think the hook should be triggered in `CartAddress`. The `CartAddress` module does not store in the member's address book. Or did I get something wrong?

**Comment by qzminski** [comment]
I was unsure about that. Does it not store it here?

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Module/CartAddress.php#L134

**Comment by aschempp** [comment]
Yeah, it potentially alters your default billing address. But it could also be a temporary cart address, we don't know. If you look at the example in #1473 I don't think it would make sense to send a notification in the cart address module.

**Comment by qzminski** [comment]
Reverted in 2045fb3.

**Comment by aschempp** [comment]
Now looking at it in detail, I wonder why we need a hook if there is the `onsubmit_callback`? @Zeromax

**Comment by Zeromax** [comment]
I can not remember why this was needed. I have a new Job and I am not able to reproduce this all in my head... Sorry about that.

Is both available in the onsubmit_callback? Than maybe I missed this callback or it has to less information...

**Comment by aschempp** [comment]
Well there's not reason not to add it anyway :D

**Comment by Zeromax** [comment]
@aschempp thanks

**Pull request merged**
