### PR TITLE
Please use releases instead of the dev-master

### PR DESCRIPTION
**Pull request by Petschko**
Same as here: https://github.com/dreipunktnull/DpnDHLBundle/pull/2

I would love, when you start to use my releases instead of the master-branch.

### CODE REVIEW

**Comment by aschempp** [comment]
Thanks a lot for your contributions! If I remember correctly, I used the master branch because there were no releases, or they were not updated to the latest changes. But I'm happily using the release version if available.

Is a `0.x` version intended for now? You're aware that `^0.3` will not install version 0.4, because 0-versions are allowed to break compatibility in every minor version?

**Comment by Petschko** [comment]
I usually support backward-compatibility, even when I'm in Version <1.0

I mark old methods as deprecated and remove them some Versions later (It shows up in your PHP-Error log, when you use a deprected method)

To be honest I'm quite close to jump on Version 1.0, just need some more testing and add one method.

**Comment by aschempp** [comment]
Please let me know when you're at `1.0` then please 😊

**Comment by Petschko** [comment]
Alright, I will^^

**Pull request closed without merging**
