### PR TITLE
fix sql cache file creation on Windows

### PR DESCRIPTION
**Pull request by fritzmg**
Under Windows, the following error might occur, when creating new attributes in the shop configuration:
```
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: mkdir(): No such file or directory

  at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php:84
  at Contao\Files->mkdir('[C:\\Users\\fritzmg\\www\\contao4]\\var\\cache\\dev')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\Folder.php:93)
  at Contao\Folder->__construct('[C:\\Users\\fritzmg\\www\\contao4]\\var\\cache\\dev/contao/sql')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php:560)
  at Contao\File->close()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Backend\Attribute\DatabaseUpdate.php:99)
  at Isotope\Backend\Attribute\DatabaseUpdate->dumpCacheFile()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Backend\Attribute\DatabaseUpdate.php:30)
  at Isotope\Backend\Attribute\DatabaseUpdate->onSubmit(object(DC_Table))
     (vendor\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php:2108)
  at Contao\DC_Table->edit()
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\BackendModule\BackendOverview.php:232)
  at Isotope\BackendModule\BackendOverview->getModule('attributes')
     (vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\BackendModule\BackendOverview.php:68)
  at Isotope\BackendModule\BackendOverview->generate()
     (vendor\contao\core-bundle\src\Resources\contao\classes\Backend.php:423)
  at Contao\Backend->getBackendModule('iso_setup', null)
     (vendor\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:132)
  at Contao\BackendMain->run()
     (vendor\contao\core-bundle\src\Controller\BackendController.php:55)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\app_dev.php:69)
```
This is because `TL_ROOT` isn't actually removed from the `kernel.cache_dir` due to the directory separator mismatch. Thus `\Contao\Files` will want to create a new directory under
```
C:\Users\fritzmg\www\contao4/C:\Users\fritzmg\www\contao4\var\cache\dev
```
which of course will not work.

### CODE REVIEW

**Comment by aschempp** [comment]
Shouldn't we rather use `Symfony\Filesystem::makePathRelative` or something like that (not sure about the exact method name)?

**Comment by aschempp** [comment]
Also, why the hell does Isotope generate an SQL cache file? 😂

**Comment by fritzmg** [comment]
> Shouldn't we rather use `Symfony\Filesystem::makePathRelative` or something like that (not sure about the exact method name)?

Sure, I can update the PR accordingly :). Using `DIRECTORY_SEPARATOR` was simply the quickest solution - but not very elegant …

> Also, why the hell does Isotope generate an SQL cache file? 😂

Hmm... as far as I understand it, you need to do it because otherwise the dynamically added table field, when adding a new product attribute, will not be recognized by Contao (or at least the Install Tool).

**Comment by fritzmg** [comment]
PR updated with using `makePathRelative` from the Symfony Filesystem Component.

**Pull request merged**
